version: "3"
services: 
  nodejsapp:
    deploy:
      replicas: 1
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - "3000:3000"
    environment: 
      - DEBUG=1
      - CHOKIDAR_USEPOLLING=true
    depends_on:
       - "javaapp"
  javaapp:
    build:
      context: D:\docker-workspace
      dockerfile: Dockerfile.txt
    ports:
      - "8080:8080"
    volumes:
      - D:\ELK:/app/images
  